services:
  db:
    image: postgres:16
    container_name: appointment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointment_booking_system
    ports:
      - "5432:5432"
    volumes:
      - appointment_pgdata:/var/lib/postgresql/data

volumes:
  appointment_pgdata:
